language: r

sudo: required

r_packages:
  - VGAM, magic, gamlss.dist, MASS, quadprog, corpcor, mvtnorm, coda, knitr

r_github_packages:
  - hadley/testthat

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change
